### ISSUE TITLE
mootools tooltip not working on lightface

### ISSUE THREAD

**Issue by kaushikam** [darkwing/LightFace#3]
I am using lightface.request and loading content from another page. I want mootools tooltip on the form elements in the lightface, but the tool tips are not getting displayed. When I removed the light face css file tool tips are getting displayed

**Comment by SitePenDavidWalsh** [comment]
The stylesheet shouldn't be the problem.  There may be a z-index issue with your tooltips.  Trying playing with the z-indexes of your tooltips and your LightFace.

**Comment by kaushikam** [comment]
Thanks, I have solved it. The z-index property of the lightface fas 9001, I changed the z-index of my tooltip to 9002 and it worked. One more thing I changed "position" of the tooltip to "relative"

**Comment by kaushikam** [comment]
Now the problem is with IE. In IE7 that z-index problem still exists. In firefox and chrome (where esc key works) after pressing esc key tool tip stays in the page after the light face dialog exits.

**Comment by kaushikam** [comment]
I changed the onShow function of the "Tips" like as follows: 

onShow: function() {
  this.Tip.setStyles({
              "display":"block",
              "z-index" : 9009
        });
}

and it worked.
